name: Security Scanner CI AlToro Mutual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Trivy CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Trivy file system scan (json output)
      run: trivy fs . --format json --output trivy-results.json || echo "Trivy scan completed with issues"

    - name: List files in repo
      run: ls -la

    - name: Show Trivy JSON preview
      run: head -20 trivy-results.json || echo "No trivy-results.json to preview"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: trivy-results.json
