name: OWASP Dependency-Check Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install OWASP Dependency-Check
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check.zip -d dependency-check
        sudo mv dependency-check /opt/dependency-check
        sudo ln -s /opt/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check
        chmod +x /usr/local/bin/dependency-check

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run OWASP Dependency-Check
      run: |
        dependency-check --project "AltoroJ" \
                         --scan . \
                         --format "HTML,CSV,JSON" \
                         --out reports \
                         --failOnCVSS 7

    - name: List reports
      run: ls -l reports

    - name: Upload dependency-check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/
