name: Security Scanner CI AlToro Mutual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Ejecutar Fluid usando Docker
    - name: Run Fluid Security Scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo -w /repo fluidattacks/scan scan run --output fluid-results.csv --format csv || echo "Fluid scan completed with issues"

    # Instalar Trivy CLI
    - name: Install Trivy CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Trivy file system scan
      run: |
        trivy fs . --format csv --output trivy-results.csv || echo "Trivy scan completed with issues"

    # Listar archivos para verificar que se generaron
    - name: List files
      run: ls -la

    # Subir archivos CSV como artefactos
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: |
          fluid-results.csv
          trivy-results.csv
