name: Security Scanner CI AlToro Mutual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Instalar Trivy CLI
    - name: Install Trivy CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    # Ejecutar Trivy y generar CSV
    - name: Run Trivy file system scan
      run: |
        trivy fs . --format csv --output trivy-results.csv || echo "Trivy scan completed with issues"
        ls -la trivy-results.csv || echo "trivy-results.csv not found"

    # Mostrar preview del resultado
    - name: Show Trivy CSV preview
      run: head -10 trivy-results.csv || echo "No trivy-results.csv to preview"

    # Subir artefactos con los resultados
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: trivy-results.csv
