name: Security Scanner CI AlToro Mutual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Trivy CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Trivy file system scan (stdout)
      run: trivy fs . --format table || echo "Trivy scan completed with issues"

    - name: Run Trivy file system scan (csv output)
      run: trivy fs . --format csv --output trivy-results.csv || echo "Trivy scan completed with issues"

    - name: List files in repo
      run: ls -la

    - name: Show Trivy CSV preview
      run: head -10 trivy-results.csv || echo "No trivy-results.csv to preview"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: trivy-results.csv
