name: OWASP Dependency-Check and Semgrep Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Download and Extract OWASP Dependency-Check
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check.zip -d dependency-check

    - name: Run OWASP Dependency-Check
      run: |
        mkdir -p reports
        ./dependency-check/dependency-check/bin/dependency-check.sh \
          --project "AltoroJ" \
          --scan . \
          --format ALL \
          --out reports \
          # --failOnCVSS 7

    - name: Upload Dependency-Check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/

    - name: Install Semgrep
      run: |
        python3 -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep scan
      run: |
        semgrep --config=auto --json --output=semgrep-results.json

    - name: Upload Semgrep results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep-results.json
