name: OWASP Dependency-Check Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Run OWASP Dependency-Check
      uses: jeremylong/DependencyCheck@v2
      with:
        project: 'AltoroJ'
        scanPath: '.'
        format: 'ALL'  # genera HTML, XML, JSON
        failBuildOnCVSS: '7'  # falla si CVSS >= 7 (alto riesgo)

    - name: Upload reports as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: |
          dependency-check-report.html
          dependency-check-report.xml
          dependency-check-report.json
