name: OWASP Dependency-Check Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install OWASP Dependency-Check
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
        unzip dependency-check.zip -d dependency-check
        sudo mv dependency-check /opt/dependency-check
        sudo chmod +x /opt/dependency-check/bin/dependency-check.sh
        sudo ln -s /opt/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check

    - name: Run OWASP Dependency-Check
      run: |
        dependency-check --project "AltoroJ" \
                         --scan . \
                         --format "ALL" \
                         --out reports \
                         --enableExperimental \
                         --log reports/dependency-check.log \
                         --failOnCVSS 7 || echo "Scan completed with issues"

    - name: Show report files
      run: |
        echo "Contenido de reports/:"
        ls -la reports || echo "reports/ no existe"

    - name: Upload dependency-check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/
